ALTER TABLE projetos ADD COLUMN IF NOT EXISTS causas TEXT NOT NULL DEFAULT '';
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS consequencias_diretas TEXT NOT NULL DEFAULT '';
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS objetivos TEXT NOT NULL DEFAULT '';
